// Action Types
export const ADD_TAGS_FILTER = 'ADD_TAGS_FILTER';
export const ADD_BRANDS_FILTER = 'ADD_BRANDS_FILTER';
export const ADD_SORT_FILTER = 'ADD_SORT_FILTER';
export const ADD_ITEM_TYPE_FILTER = 'ADD_ITEM_TYPE_FILTER';
